groups:
  - name: ai-morphasis.rules
    rules:
      - record: job:http_inference_latency_p95
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, job))
