apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-morphasis
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - ai-morphasis-deployment.yaml
  - tensorflow-serving-deployment.yaml
  - training-job.yaml
  - service.yaml
  - hpa.yaml
